{
 "title": "Replication",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ACL Token Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_leader_replication_acl_tokens_status"
    }
   ]
  },
  {
   "title": "ACL Role Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_leader_replication_acl_roles_status"
    }
   ]
  },
  {
   "title": "ACL Policies Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_leader_replication_acl_policies_status"
    }
   ]
  },
  {
   "title": "Federation State Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_leader_replication_federation_state_status"
    }
   ]
  },
  {
   "title": "Config Entry Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_leader_replication_config_entries_status"
    }
   ]
  },
  {
   "title": "Namespace Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_leader_replication_namespaces_status"
    }
   ]
  }
 ]
}